= pasfetch(1)
Marie Eckert
v2.0.0
:doctype: manpage
:manmanual: PASFETCH
:mansource: PASFETCH
:man-linkstyle: pass:[blue R < >]

== Name

pasfetch - A System fetch program written in Pascal.

== Synposis

*pasfetch* [-n] [-c] [-C] [-i] [-is] [-ts] [-ls]

== Options

*-n*::
	Do not try to load the configuration file

*-c*::
	Disables colored output.
	Overrides the value of `nocolor` in the config.

*-C <color>*::
	Override the color used for colored parts.
	Overrides the value of `overridecolor` in the config.
	Color can be one of the following:
		- black
		- red
		- green
		- yellow
		- blue
		- magenta
		- cyan
		- white
		- brightblack
		- brightred
		- brightgreen
		- brightyellow
		- brightblue
		- brightmagent
		- brightcyan
		- brightwhite

*-i <infos>*::
	Specify what information points should be listed in a comma seperated list.
	All points must be prefixed with either `fl:` or `env:`. Points prefixed
	with `fl:` are things that pasfetch fetches internally, points prefixed with
	`env:` are environment variables.
	Overrides the value of `infos` in the config.
	Valid `fl:` points are:
		- `fl:MEM` Memory usage in kB
		- `fl:OS` Operating System name
		- `fl:KERNEL` Kernel Version
		- `fl:UPTIME` System Uptime
		- `fl:CPU` The CPU model name
		- `fl:HOST` The modelname of the host system
		- `fl:HOSTNAME` The system's hostname
		- `fl:USERATHOSTNAME` The hostname appended to the current user's name with an @ seperating the two.
		- `fl:PKGS` Number of installed packages.

*-is <style>*::
	Specify the styling for the the information point labels. Multiple styles
	can be stacked using commas as seperators.
	Overrides the value of `infolabelstyle` in the config.
	Valid styles are:
		- normal
		- bold
		- dim
		- italic
		- underline
		- slowblink
		- rapidblink
		- reverse

*-ts*::
	Specify the styling for the information point values. Multiple styles
	can be stacked using commas as seperators.
	Overrides the value of `infotextstyle` in the config.
	For valid styles, see the list in the reference for `-is`.

*-ls*::
	Specify the styling for the logo. Multiple styles can be stacked using
	commas as seperators.
	Overrides the value of `infotextstyle` in the config.
	For valid styles, see the list in the reference for `-is`.

== Configuration

=== Location

pasfetch searches for a configuration in the following places:
	1. $XDG_CONFIG_HOME/pasfetch/config.ini
	2. $HOME/.pasfetch.ini
	3. /etc/pasfetch.ini

=== Configuring

The configuration is a list of ini-values all within the `PASFETCH` section.
Accepted configuration points are:
	- color
	- infos
	- infolabelstyle
	- infotextstyle
	- logostyle
	- overridecolor

Every one of these values can be overriden using a commandline option.

*nocolor=<true|false>*::
	Disables colored output if set to true.

*color=<color>*::
	Override the color used for colored parts.
	Color can be one of the following:
		- black
		- red
		- green
		- yellow
		- blue
		- magenta
		- cyan
		- white
		- brightblack
		- brightred
		- brightgreen
		- brightyellow
		- brightblue
		- brightmagent
		- brightcyan
		- brightwhite

*infos=<infos>*::
	Specify what information points should be listed in a comma seperated list.
	All points must be prefixed with either `fl:` or `env:`. Points prefixed
	with `fl:` are things that pasfetch fetches internally, points prefixed with
	`env:` are environment variables.
	Valid `fl:` points are:
		- `fl:MEM` Memory usage in kB
		- `fl:OS` Operating System name
		- `fl:KERNEL` Kernel Version
		- `fl:UPTIME` System Uptime
		- `fl:CPU` The CPU model name
		- `fl:HOST` The modelname of the host system
		- `fl:HOSTNAME` The system's hostname
		- `fl:USERATHOSTNAME` The hostname appended to the current user's name with an @ seperating the two.
		- `fl:PKGS` Number of installed packages.

*infolabelstyle=<style(s)>*::
	Specify the styling for the the information point labels. Multiple styles
	can be stacked using commas as seperators.
	Valid styles are:
		- normal
		- bold
		- dim
		- italic
		- underline
		- slowblink
		- rapidblink
		- reverse

*infotextstyle=<style(s)>*::
	Specify the styling for the information point values. Multiple styles
	can be stacked using commas as seperators.
	For valid styles, see the list in the reference for `infolabelstyle`.

*logostyle=<style(s)>*::
	Specify the styling for the logo. Multiple styles can be stacked using
	commas as seperators.
	For valid styles, see the list in the reference for `infolabelstyle`.

=== Example

	[PASFETCH]
	color=cyan
	infos=env:USER,fl:HOST,fl:KERNEL,fl:OS,fl:PKGS,env:SHELL,env:TERM,fl:UPTIME,fl:CPU,fl:MEM
	infotextstyle=italic
	infolabelstyle=bold
	logostyle=bold

== Copying

Copyright (c) 2025, {author}. +
This software is licensed under the ISC license.

== Contributors

array-in-a-matrix, polluks
