{
	vim: filetype=pascal
}

function Host: String;
begin
	result := 'TODO';
end;

function OsName: String;
begin
	result := 'TODO';
end;

function CPU: String;
begin
	result := 'TODO';
end;

function PkgCount: String;
begin
	result := 'TODO';
end;

function Uptime: String;
begin
	result := 'TODO';
end;

function MemoryUsage: String;
begin
	result := 'TODO';
end;

function Kernel: String;
begin
	result := 'TODO';
end;
